#!/usr/bin/python

import sys
import socket
import time
import datetime
import select
import json

MSG_SIZE = 1500
TIMEOUT = 30

# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
UDP_PORT = 0

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
UDP_PORT = sock.getsockname()[1]
#log("[bound] " + str(UDP_PORT))


def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

# Now listen for packets
while True:
    result = sock.recvfrom(MSG_SIZE)
    if result:
        (data, addr) = result

        try:
            data_json = json.loads(data)

            # if at the end of the message
            if data_json['eof']:
                log("[Mission Completed!]")
                sys.exit(0)

            if data_json['data']:
                log("[recv data] " + str(data_json['seq_num']) + " (" + str(len(data_json['data'])) + ") ACCEPTED (in-order)")
                sys.stdout.write(data_json['data'])
                log("in 3700recv %s" % data_json)
        except (ValueError, KeyError, TypeError) as e:
            print("received corrupted packet")
            raise e
    else:
        log("[ERROR] socket timed out after %d seconds!" % TIMEOUT)
        sys.exit(-1)

