#!/usr/bin/python

import sys
import socket
import time
import datetime
import select
import json
from packets import *

MSG_SIZE = 1500
TIMEOUT = 30
seq = 0

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
UDP_PORT = 0

# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
UDP_PORT = sock.getsockname()[1]
log("[bound] " + str(UDP_PORT))

buffered_packets = []

def sack(ack_packet):
    sock.sendto(json.dumps(ack_packet.as_json()), (UDP_IP, UDP_PORT))

def receive_enqueue_ack():
    result = sock.recvfrom(MSG_SIZE)
    if result:
        (data, addr) = result

        try:
            data_json = json.loads(data)

            # if at the end of the message
            if data_json['eof']:
                sys.stdout.write(data_json['data'])
                log("[Mission Completed!]")
                sys.exit(0)

            if data_json['data']:
                log("[recv data] " + str(data_json['seq_num']) + " (" + str(len(data_json['data'])) + ") ACCEPTED (in-order)")
                buffered_packets.append(data_json)
                ack = AckPacket(data_json['seq_num'])
                sack(ack)
                
                #sys.stdout.write(data_json['data'])
        except (ValueError, KeyError, TypeError) as e:
            print("received corrupted packet")
            raise e

def process():
        

# Now listen for packets
while True:
#TODO: send ack, organize by seq #
# receive/enqueue data
# process data/send ack
    receive_enqueue_ack()
    process()

"""
    else:
        log("[ERROR] socket timed out after %d seconds!" % TIMEOUT)
        sys.exit(-1)
"""
